<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  
'Add Translation' => 'Добавить перевод',
  'Add Translations' => 'Добавить переводы',
  'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
  'Author' => 'Автор',
  'Blogs' => 'Блоги',
  'Change description' => 'Изменить описание',
  'Change highlighted text' => 'Изменить выделенный текст',
  'Change title' => 'Изменить заголовок',
  'Coffee Categories' => 'Категории кофе',
  'Coffee Image' => 'Изображение кофе',
  'Coffees' => 'Кофе',
  'Comments' => 'Комментарии',
  'Create Blog' => 'Создать блог',
  'Create Coffee' => 'Создать кофе',
  'Create Coffee Category' => 'Создать категорию кофе',
  'Create Comment' => 'Создать комментарий',
  'Create Item' => 'Создать элемент',
  'Create Newsletter Subscriber' => 'Создать подписчика на новости',
  'Create Order' => 'Создать заказ',
  'Create Product' => 'Создать продукт',
  'Create Site Info' => 'Создать информацию о сайте',
  'Create Sponsor' => 'Создать спонсора',
  'Create Text Source' => 'Создать источник текста',
  'Create Text Translation' => 'Создать перевод текста',
  'Delete' => 'Удалить',
  'Description' => 'Описание',
  'Highlighted Text' => 'Выделенный текст',
  'Image' => 'Изображение',
  'Image Upload' => 'Загрузка изображения',
  'Image layer 1' => 'Изображение слоя 1',
  'Image layer 2' => 'Изображение слоя 2',
  'Items' => 'Элементы',
  'Layer 1' => 'Слой 1',
  'Layer 1 image' => 'Изображение слоя 1',
  'Layer 2' => 'Слой 2',
  'Layer 2 image' => 'Изображение слоя 2',
  'Main Image' => 'Основное изображение',
  'Main product' => 'Основной продукт',
  'Newsletter Subscribers' => 'Подписчики на рассылку',
  'Orders' => 'Заказы',
  'Products' => 'Продукты',
  'Reset' => 'Сбросить',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Site Info' => 'Информация о сайте',
  'Site Infos' => 'Информации о сайте',
  'Source' => 'Источник',
  'Sponsors' => 'Спонсоры',
  'Text Sources' => 'Источники текста',
  'Text Translations' => 'Переводы текста',
  'The requested page does not exist.' => 'Запрашиваемая страница не существует.',
  'Thumbnail Image' => 'Миниатюра',
  'Title' => 'Заголовок',
  'Translations' => 'Переводы',
  'Update' => 'Обновить',
  'Update Blog: {name}' => 'Обновить блог: {name}',
  'Update Coffee Category: {name}' => 'Обновить категорию кофе: {name}',
  'Update Coffee: {name}' => 'Обновить кофе: {name}',
  'Update Comment: {name}' => 'Обновить комментарий: {name}',
  'Update Item: {name}' => 'Обновить элемент: {name}',
  'Update Newsletter Subscriber: {name}' => 'Обновить подписчика: {name}',
  'Update Order: {name}' => 'Обновить заказ: {name}',
  'Update Product: {name}' => 'Обновить продукт: {name}',
  'Update Site Info: {name}' => 'Обновить информацию о сайте: {name}',
  'Update Sponsor: {name}' => 'Обновить спонсора: {name}',
  'Update Text Source: {name}' => 'Обновить источник текста: {name}',
  'Update Text Translation: {name}' => 'Обновить перевод текста: {name}',
  'Upload' => 'Загрузить',
];
