<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Choose Your Favorite Coffee And Enjoy ' => 'Выберите свой любимый кофе и наслаждайтесь',
    'Add to Cart' => 'Добавить в корзину',
    'Address' => 'Адрес',
    'Blog' => 'Блог',
    'Blog Title: {title}' => 'Название блога: {title}',
    'Buy the best and delicious coffees.' => 'Покупайте лучший и самый вкусный кофе.',
    'Cart' => 'Корзина',
    'Checkout' => 'Оформление заказа',
    'Choose our delicious and best products' => 'Выбирайте наши вкусные и лучшие продукты',
    'Comments {count}' => 'Комментарии {count}',
    'Contact' => 'Контакты',
    'Content: {content}' => 'Содержание: {content}',
    'Delicious Cookies' => 'Вкусное печенье',
    'Enjoy at Home' => 'Наслаждайтесь дома',
    'Enjoy the best coffee in the comfort of your home.' => 'Наслаждайтесь лучшим кофе в комфорте вашего дома.',
    'Enjoy your coffee with some hot cookies' => 'Пейте кофе с горячим печеньем',
    'Exclusive Product' => 'Эксклюзивный продукт',
    'Home' => 'Главная',
    'No comments yet.' => 'Пока нет комментариев.',
    'Office' => 'Офис',
    'Our Blogs Coffee with trending topic for this week' => 'Наши блоги с популярными темами недели о кофе',
    'Place Order' => 'Оформить заказ',
    'Please fill out both fields before submitting.' => 'Пожалуйста, заполните оба поля перед отправкой.',
    'Please provide your details to complete the order.' => 'Пожалуйста, укажите свои данные для завершения заказа.',
    'Please {loginLink} or {registerLink} to post a comment.' => 'Пожалуйста, {loginLink} или {registerLink}, чтобы оставить комментарий.',
    'Post Comment' => 'Оставить комментарий',
    'Post a Comment' => 'Написать комментарий',
    'Posted on {date} by {author}' => 'Опубликовано {date} автором {author}',
    'Premium' => 'Премиум',
    'Premium preparation with quality ingredients.' => 'Премиум-качество с лучшими ингредиентами.',
    'Proceed to Checkout' => 'Перейти к оформлению заказа',
    'Products' => 'Продукты',
    'Review and adjust your order before checkout.' => 'Просмотрите и отредактируйте заказ перед оформлением.',
    'Selected Coffee' => 'Выбранный кофе',
    'Specialty coffees that make you happy and cheer you up!' => 'Особые сорта кофе, которые поднимут настроение!',
    'Subscribe to our newsletter' => 'Подпишитесь на нашу рассылку',
    'Total' => 'Итого',
    'Views: {count}' => 'Просмотры: {count}',
    'We offer a premium and better quality preparation just for you!' => 'Мы предлагаем премиум-качество специально для вас!',
    'We select the best premium coffee, for a true taste.' => 'Мы выбираем лучший премиум-кофе для истинного вкуса.',
    'Web Design Illustration' => 'Иллюстрация веб-дизайна',
    'Your Cart' => 'Ваша корзина',
    'Your Cart is empty' => 'Ваша корзина пуста',
    'Your address' => 'Ваш адрес',
    'Your email...' => 'Ваш email...',
    'Your phone number' => 'Ваш номер телефона',
    'login' => 'вход',
    'register' => 'регистрация',
    'Login' => '',
    'Logout' => '',
    '{count} products' => '',
    '{logouttext}' => '',
];
