<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Address' => 'Manzil',
  'Auth Key' => 'Autentifikatsiya kodi',
  'Author ID' => 'Muallif ID',
  'Blog ID' => 'Blog ID',
  'Body' => 'Matn',
  'Cart ID' => 'Savat ID',
  'Category ID' => 'Kategoriya ID',
  'Comment Text' => 'Izoh matni',
  'Created At' => 'Yaratilgan vaqti',
  'Description Text Source ID' => 'Tavsif matni manba ID',
  'Email' => 'Elektron pochta',
  'End Time' => 'Tugash vaqti',
  'End Week' => 'Tugash haftasi',
  'Facebook Url' => 'Facebook URL',
  'ID' => 'ID',
  'Image Layer 1' => 'Rasm qavati 1',
  'Image Layer 2' => 'Rasm qavati 2',
  'Image Path' => 'Rasm yo‘li',
  'Instagram Url' => 'Instagram URL',
  'Label' => 'Etiket',
  'Language Code' => 'Til kodi',
  'Main Image' => 'Asosiy rasm',
  'Name' => 'Ism',
  'Object ID' => 'Obyekt ID',
  'Order ID' => 'Buyurtma ID',
  'Password Hash' => 'Parol xeshi',
  'Password Reset Token' => 'Parolni qayta tiklash tokeni',
  'Payment Type' => 'To‘lov turi',
  'Phone Number' => 'Telefon raqami',
  'Price' => 'Narxi',
  'Secondary Address' => 'Ikkinchi manzil',
  'Slug' => 'Slug',
  'Start Time' => 'Boshlanish vaqti',
  'Start Week' => 'Boshlanish haftasi',
  'Status' => 'Status',
  'Telegram Url' => 'Telegram URL',
  'Text Source ID' => 'Matn manba ID',
  'Thumbnail Image' => 'Mini rasm',
  'Title' => 'Sarlavha',
  'Title Text Source ID' => 'Sarlavha matni manba ID',
  'Translated description' => 'Tarjima qilingan tavsif',
  'Translated title for Coffee' => 'Kofe uchun tarjima qilingan sarlavha',
  'Translation' => 'Tarjima',
  'Type' => 'Tur',
  'Updated At' => 'Yangilangan vaqti',
  'User ID' => 'Foydalanuvchi ID',
  'Username' => 'Foydalanuvchi nomi',
  'Verification Token' => 'Tasdiq tokeni',
  'Views' => 'Ko‘rishlar',
  'Cash' => '',
  'Click' => '',
  'Default text' => '',
  'Payme' => '',
];
