<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Add Translation' => 'Таржимани қўшиш',
  'Add Translations' => 'Таржималарни қўшиш',
  'Are you sure you want to delete this item?' => 'Ушбу элементни ўчиришга ишончингиз комилми?',
  'Author' => 'Муаллиф',
  'Blogs' => 'Блоглар',
  'Change description' => 'Тавсифни ўзгартириш',
  'Change highlighted text' => 'Ажратилган матнни ўзгартириш',
  'Change title' => 'Сарлавҳани ўзгартириш',
  'Coffee Categories' => 'Кофе тоифалари',
  'Coffee Image' => 'Кофе расми',
  'Coffees' => 'Кофе',
  'Comments' => 'Изоҳлар',
  'Create Blog' => 'Блог яратиш',
  'Create Coffee' => 'Кофе яратиш',
  'Create Coffee Category' => 'Кофе тоифасини яратиш',
  'Create Comment' => 'Изоҳ яратиш',
  'Create Item' => 'Элемент яратиш',
  'Create Newsletter Subscriber' => 'Янгиликлар обуначисини яратиш',
  'Create Order' => 'Буюртма яратиш',
  'Create Product' => 'Маҳсулот яратиш',
  'Create Site Info' => 'Сайт ҳақида маълумот яратиш',
  'Create Sponsor' => 'Ҳомий яратиш',
  'Create Text Source' => 'Матн манбасини яратиш',
  'Create Text Translation' => 'Матн таржимасини яратиш',
  'Delete' => 'Ўчириш',
  'Description' => 'Тавсиф',
  'Highlighted Text' => 'Ажратилган матн',
  'Image' => 'Расм',
  'Image Upload' => 'Расм юклаш',
  'Image layer 1' => '1-қават расми',
  'Image layer 2' => '2-қават расми',
  'Items' => 'Элементлар',
  'Layer 1' => '1-қават',
  'Layer 1 image' => '1-қават расми',
  'Layer 2' => '2-қават',
  'Layer 2 image' => '2-қават расми',
  'Main Image' => 'Асосий расм',
  'Main product' => 'Асосий маҳсулот',
  'Newsletter Subscribers' => 'Ахборотномага обуначилар',
  'Orders' => 'Буюртмалар',
  'Products' => 'Маҳсулотлар',
  'Reset' => 'Қайта тиклаш',
  'Save' => 'Сақлаш',
  'Search' => 'Қидириш',
  'Site Info' => 'Сайт ҳақида маълумот',
  'Site Infos' => 'Сайт ҳақида маълумотлар',
  'Source' => 'Манба',
  'Sponsors' => 'Ҳомийлар',
  'Text Sources' => 'Матн манбалари',
  'Text Translations' => 'Матн таржималари',
  'The requested page does not exist.' => 'Сўралган саҳифа мавжуд эмас.',
  'Thumbnail Image' => 'Миниатюра расм',
  'Title' => 'Сарлавҳа',
  'Translations' => 'Таржималар',
  'Update' => 'Янгилаш',
  'Update Blog: {name}' => 'Блогни янгилаш: {name}',
  'Update Coffee Category: {name}' => 'Кофе тоифасини янгилаш: {name}',
  'Update Coffee: {name}' => 'Кофени янгилаш: {name}',
  'Update Comment: {name}' => 'Изоҳни янгилаш: {name}',
  'Update Item: {name}' => 'Элементни янгилаш: {name}',
  'Update Newsletter Subscriber: {name}' => 'Обуначини янгилаш: {name}',
  'Update Order: {name}' => 'Буюртмани янгилаш: {name}',
  'Update Product: {name}' => 'Маҳсулотни янгилаш: {name}',
  'Update Site Info: {name}' => 'Сайт маълумотини янгилаш: {name}',
  'Update Sponsor: {name}' => 'Ҳомийни янгилаш: {name}',
  'Update Text Source: {name}' => 'Матн манбасини янгилаш: {name}',
  'Update Text Translation: {name}' => 'Матн таржимасини янгилаш: {name}',
  'Upload' => 'Юклаш',
];
