<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Choose Your Favorite Coffee And Enjoy ' => 'Tanlang va kofeni bahramand bo‘ling',
    'Add to Cart' => 'Savatchaga qo‘shish',
    'Address' => 'Manzil',
    'Blog' => 'Blog',
    'Blog Title: {title}' => 'Blog Sarlavhasi: {title}',
    'Buy the best and delicious coffees.' => 'Eng mazali va yaxshi kofeni sotib oling.',
    'Cart' => 'Savat',
    'Checkout' => 'Chiqish',
    'Choose our delicious and best products' => 'Mazali va eng yaxshi mahsulotlarimizni tanlang',
    'Comments {count}' => 'Sharhlar {count}',
    'Contact' => 'Bog‘lanish',
    'Content: {content}' => 'Mazmun: {content}',
    'Delicious Cookies' => 'Mazali kukilar',
    'Enjoy at Home' => 'Uyda bahramand bo‘ling',
    'Enjoy the best coffee in the comfort of your home.' => 'Uyishingizda eng yaxshi kofeni bahramand qiling.',
    'Enjoy your coffee with some hot cookies' => 'Kofeni issiq kukilar bilan iste’mol qiling',
    'Exclusive Product' => 'Eksklyuziv mahsulot',
    'Home' => 'Bosh sahifa',
    'No comments yet.' => 'Hali sharhlar yoʻq.',
    'Office' => 'Ofis',
    'Our Blogs Coffee with trending topic for this week' => 'Bloglarimizdagi ushbu haftadagi trend mavzular bilan qahva',
    'Place Order' => 'Buyurtma berish',
    'Please fill out both fields before submitting.' => 'Iltimos, yuborishdan oldin ikkita maydonni toʻldiring.',
    'Please provide your details to complete the order.' => 'Buyurtmani ro‘yxatdan o‘tkazish uchun ma’lumotlaringizni kiriting.',
    'Please {loginLink} or {registerLink} to post a comment.' => 'Iltimos, sharh yozish uchun {loginLink} yoki {registerLink} qiling.',
    'Post Comment' => 'Sharhni Yuborish',
    'Post a Comment' => 'Sharh Yozish',
    'Posted on {date} by {author}' => '{date}-kuni  {author} tomonidan yozilgan',
    'Premium' => 'Premium',
    'Premium preparation with quality ingredients.' => 'Sifatli mahsulotlar bilan premium tayyorlov.',
    'Proceed to Checkout' => 'Buyurtmani rasmiylashtirish',
    'Products' => 'Mahsulotlar',
    'Review and adjust your order before checkout.' => 'Buyurtmani rasmiylashtirishdan oldin ko‘rib chiqing va o‘zgartiring.',
    'Selected Coffee' => 'Tanlangan qahva',
    'Specialty coffees that make you happy and cheer you up!' => 'Kayfiyatingizni ko‘taruvchi maxsus qahvalar!',
    'Subscribe to our newsletter' => 'Yangiliklar xabariga obuna bo‘ling',
    'Total' => 'Jami',
    'Views: {count}' => 'Koʻrishlar: {count}',
    'We offer a premium and better quality preparation just for you!' => 'Siz uchun premium va yuqori sifatli tayyorlov taklif qilamiz!',
    'We select the best premium coffee, for a true taste.' => 'Chin mazza uchun eng yaxshi premium qahvani tanlaymiz.',
    'Web Design Illustration' => 'Web Dizayn Illyustratsiyasi',
    'Your Cart' => 'Savatangiz',
    'Your Cart is empty' => 'Savatangiz bo‘sh',
    'Your address' => 'Sizning manzilingiz',
    'Your email...' => 'Elektron pochtangizni kiriting...',
    'Your phone number' => 'Sizning telefon raqamingiz',
    'login' => 'kirish',
    'register' => 'roʻyxatdan oʻtish',
    'Login' => '',
    'Logout' => '',
    '{count} products' => '',
];
