<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Choose Your Favorite Coffee And Enjoy ' => 'Танланг ва кофени баҳраманд бўлинг',
    'Add to Cart' => 'Саватчага қўшиш',
    'Address' => 'Манзил',
    'Blog' => 'Блог',
    'Blog Title: {title}' => 'Блог Сарлавҳаси: {title}',
    'Buy the best and delicious coffees.' => 'Энг мазали ва яхши кофени сотиб олинг.',
    'Cart' => 'Сават',
    'Checkout' => 'Чиқиш',
    'Choose our delicious and best products' => 'Мазали ва энг яхши маҳсулотларимизни танланг',
    'Comments {count}' => 'Шарҳлар {count}',
    'Contact' => 'Боғланиш',
    'Content: {content}' => 'Мазмун: {content}',
    'Delicious Cookies' => 'Мазали кукилар',
    'Enjoy at Home' => 'Уйда баҳраманд бўлинг',
    'Enjoy the best coffee in the comfort of your home.' => 'Уйингизда энг яхши кофени баҳраманд қилинг.',
    'Enjoy your coffee with some hot cookies' => 'Кофени иссиқ кукилар билан истаъмол қилинг',
    'Exclusive Product' => 'Эксклюзив маҳсулот',
    'Home' => 'Бош саҳифа',
    'No comments yet.' => 'Ҳали шарҳлар йўқ.',
    'Office' => 'Офис',
    'Our Blogs Coffee with trending topic for this week' => 'Блогларимиздаги ушбу ҳафтадаги тренд мавзулар билан қаҳва',
    'Place Order' => 'Буюртма бериш',
    'Please fill out both fields before submitting.' => 'Илтимос, юборардан олдин икки майдонни тўлдиринг.',
    'Please provide your details to complete the order.' => 'Буюртмани рўйхатдан ўтказиш учун маълумотларни киритинг.',
    'Please {loginLink} or {registerLink} to post a comment.' => 'Илтимос, шарҳ ёзиш учун {loginLink} ёки {registerLink} қилинг.',
    'Post Comment' => 'Шарҳни Юбориш',
    'Post a Comment' => 'Шарҳ Ёзиш',
    'Posted on {date} by {author}' => '{date} куни ёзган {author}',
    'Premium' => 'Премиум',
    'Premium preparation with quality ingredients.' => 'Сифатли маҳсулотлар билан премиум тайёрлов.',
    'Proceed to Checkout' => 'Буюртмани расмийлаштириш',
    'Products' => 'Маҳсулотлар',
    'Review and adjust your order before checkout.' => 'Буюртмани расмийлаштиришдан олдин кўриб чиқинг ва ўзгартиринг.',
    'Selected Coffee' => 'Танланган қаҳва',
    'Specialty coffees that make you happy and cheer you up!' => 'Кайфингизни кўтарувчи махсус қаҳвалар!',
    'Subscribe to our newsletter' => 'Янгиликлар хабарига обуна бўлинг',
    'Total' => 'Жами',
    'Views: {count}' => 'Кўришлар: {count}',
    'We offer a premium and better quality preparation just for you!' => 'Сиз учун премиум ва юқори сифатли тайёрлов таклиф қиламиз!',
    'We select the best premium coffee, for a true taste.' => 'Чин мазза учун энг яхши премиум қаҳвани танлаймиз.',
    'Web Design Illustration' => 'Веб Дизайн Илюстрацияси',
    'Your Cart' => 'Саватингиз',
    'Your Cart is empty' => 'Саватингиз бўш',
    'Your address' => 'Сизнинг манзилингиз',
    'Your email...' => 'Электрон почтангизни киритинг...',
    'Your phone number' => 'Сизнинг телефон рақамингиз',
    'login' => 'кириш',
    'register' => 'рўйхатдан ўтиш',
    'Login' => '',
    'Logout' => '',
    '{count} products' => '',
    '{logouttext}' => '',
];
