<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Address' => 'Адрес',
  'Auth Key' => 'Ключ аутентификации',
  'Author ID' => 'ID автора',
  'Blog ID' => 'ID блога',
  'Body' => 'Тело',
  'Cart ID' => 'ID корзины',
  'Category ID' => 'ID категории',
  'Comment Text' => 'Текст комментария',
  'Created At' => 'Создано в',
  'Description Text Source ID' => 'ID источника текста описания',
  'Email' => 'Электронная почта',
  'End Time' => 'Время окончания',
  'End Week' => 'Конец недели',
  'Facebook Url' => 'URL Facebook',
  'ID' => 'ID',
  'Image Layer 1' => 'Слой изображения 1',
  'Image Layer 2' => 'Слой изображения 2',
  'Image Path' => 'Путь к изображению',
  'Instagram Url' => 'URL Instagram',
  'Label' => 'Метка',
  'Language Code' => 'Код языка',
  'Main Image' => 'Основное изображение',
  'Name' => 'Имя',
  'Object ID' => 'ID объекта',
  'Order ID' => 'ID заказа',
  'Password Hash' => 'Хеш пароля',
  'Password Reset Token' => 'Токен сброса пароля',
  'Payment Type' => 'Тип оплаты',
  'Phone Number' => 'Номер телефона',
  'Price' => 'Цена',
  'Secondary Address' => 'Вторичный адрес',
  'Slug' => 'Slug',
  'Start Time' => 'Время начала',
  'Start Week' => 'Начало недели',
  'Status' => 'Статус',
  'Telegram Url' => 'URL Telegram',
  'Text Source ID' => 'ID источника текста',
  'Thumbnail Image' => 'Миниатюра изображения',
  'Title' => 'Заголовок',
  'Title Text Source ID' => 'ID источника текста заголовка',
  'Translated description' => 'Переведенное описание',
  'Translated title for Coffee' => 'Переведенный заголовок для кофе',
  'Translation' => 'Перевод',
  'Type' => 'Тип',
  'Updated At' => 'Обновлено в',
  'User ID' => 'ID пользователя',
  'Username' => 'Имя пользователя',
  'Verification Token' => 'Токен проверки',
  'Views' => 'Просмотры',
  'Cash' => '',
  'Click' => '',
  'Default text' => '',
  'Payme' => '',
];
