<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Address' => 'Манзил',
  'Auth Key' => 'Аутентификация коди',
  'Author ID' => 'Муаллиф ID',
  'Blog ID' => 'Блог ID',
  'Body' => 'Текст',
  'Cart ID' => 'Сават ID',
  'Category ID' => 'Категория ID',
  'Comment Text' => 'Комментарий матни',
  'Created At' => 'Яратилган вақти',
  'Description Text Source ID' => 'Тасвир матни манба ID',
  'Email' => 'Электрон почта',
  'End Time' => 'Тугаш вақти',
  'End Week' => 'Тугаш ҳафтаси',
  'Facebook Url' => 'Facebook URL',
  'ID' => 'ID',
  'Image Layer 1' => 'Расм қабати 1',
  'Image Layer 2' => 'Расм қабати 2',
  'Image Path' => 'Расм йўли',
  'Instagram Url' => 'Instagram URL',
  'Label' => 'Этикет',
  'Language Code' => 'Тил коди',
  'Main Image' => 'Асосий расм',
  'Name' => 'Исм',
  'Object ID' => 'Объект ID',
  'Order ID' => 'Буюртма ID',
  'Password Hash' => 'Парол хеши',
  'Password Reset Token' => 'Паролни қайта тиклаш токени',
  'Payment Type' => 'Тўлов тури',
  'Phone Number' => 'Телефон рақами',
  'Price' => 'Нархи',
  'Secondary Address' => 'Иккинчи манзил',
  'Slug' => 'Slug',
  'Start Time' => 'Бошланиш вақти',
  'Start Week' => 'Бошланиш ҳафтаси',
  'Status' => 'Статус',
  'Telegram Url' => 'Telegram URL',
  'Text Source ID' => 'Матн манба ID',
  'Thumbnail Image' => 'Мини расм',
  'Title' => 'Сарлавҳа',
  'Title Text Source ID' => 'Сарлавҳа матни манба ID',
  'Translated description' => 'Таржима қилинган тасвир',
  'Translated title for Coffee' => 'Кофе учун таржима қилинган сарлавҳа',
  'Translation' => 'Таржима',
  'Type' => 'Тур',
  'Updated At' => 'Янгиланган вақти',
  'User ID' => 'Фойдаланувчи ID',
  'Username' => 'Фойдаланувчи номи',
  'Verification Token' => 'Тасдиқ токени',
  'Views' => 'Кўришлар',
  'Cash' => '',
  'Click' => '',
  'Default text' => '',
  'Payme' => '',
];
