<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'Add Translation' => 'Tarjimani qoʻshish',
  'Add Translations' => 'Tarjimalarni qoʻshish',
  'Are you sure you want to delete this item?' => 'Ushbu elementni oʻchirishga ishonchingiz komilmi?',
  'Author' => 'Muallif',
  'Blogs' => 'Bloglar',
  'Change description' => 'Tavsifni oʻzgartirish',
  'Change highlighted text' => 'Ajratilgan matnni oʻzgartirish',
  'Change title' => 'Sarlavhani oʻzgartirish',
  'Coffee Categories' => 'Kofe toifalari',
  'Coffee Image' => 'Kofe rasmi',
  'Coffees' => 'Kofe',
  'Comments' => 'Izohlar',
  'Create Blog' => 'Blog yaratish',
  'Create Coffee' => 'Kofe yaratish',
  'Create Coffee Category' => 'Kofe toifasini yaratish',
  'Create Comment' => 'Izoh yaratish',
  'Create Item' => 'Element yaratish',
  'Create Newsletter Subscriber' => 'Yangiliklar obunachisini yaratish',
  'Create Order' => 'Buyurtma yaratish',
  'Create Product' => 'Mahsulot yaratish',
  'Create Site Info' => 'Sayt haqida maʼlumot yaratish',
  'Create Sponsor' => 'Homiy yaratish',
  'Create Text Source' => 'Matn manbasini yaratish',
  'Create Text Translation' => 'Matn tarjimasini yaratish',
  'Delete' => 'Oʻchirish',
  'Description' => 'Tavsif',
  'Highlighted Text' => 'Ajratilgan matn',
  'Image' => 'Rasm',
  'Image Upload' => 'Rasm yuklash',
  'Image layer 1' => '1-qavat rasmi',
  'Image layer 2' => '2-qavat rasmi',
  'Items' => 'Elementlar',
  'Layer 1' => '1-qavat',
  'Layer 1 image' => '1-qavat rasmi',
  'Layer 2' => '2-qavat',
  'Layer 2 image' => '2-qavat rasmi',
  'Main Image' => 'Asosiy rasm',
  'Main product' => 'Asosiy mahsulot',
  'Newsletter Subscribers' => 'Axborotnomaga obunachilar',
  'Orders' => 'Buyurtmalar',
  'Products' => 'Mahsulotlar',
  'Reset' => 'Qayta tiklash',
  'Save' => 'Saqlash',
  'Search' => 'Qidirish',
  'Site Info' => 'Sayt haqida maʼlumot',
  'Site Infos' => 'Sayt haqida maʼlumotlar',
  'Source' => 'Manba',
  'Sponsors' => 'Homiylar',
  'Text Sources' => 'Matn manbalari',
  'Text Translations' => 'Matn tarjimalari',
  'The requested page does not exist.' => 'Soʻralgan sahifa mavjud emas.',
  'Thumbnail Image' => 'Miniatyura rasm',
  'Title' => 'Sarlavha',
  'Translations' => 'Tarjimalar',
  'Update' => 'Yangilash',
  'Update Blog: {name}' => 'Blogni yangilash: {name}',
  'Update Coffee Category: {name}' => 'Kofe toifasini yangilash: {name}',
  'Update Coffee: {name}' => 'Kofeni yangilash: {name}',
  'Update Comment: {name}' => 'Izohni yangilash: {name}',
  'Update Item: {name}' => 'Elementni yangilash: {name}',
  'Update Newsletter Subscriber: {name}' => 'Obunachini yangilash: {name}',
  'Update Order: {name}' => 'Buyurtmani yangilash: {name}',
  'Update Product: {name}' => 'Mahsulotni yangilash: {name}',
  'Update Site Info: {name}' => 'Sayt maʼlumotini yangilash: {name}',
  'Update Sponsor: {name}' => 'Homiyni yangilash: {name}',
  'Update Text Source: {name}' => 'Matn manbasini yangilash: {name}',
  'Update Text Translation: {name}' => 'Matn tarjimasini yangilash: {name}',
  'Upload' => 'Yuklash',
];
